export default {
  '1': {
    'title': 'Um',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2024-05-03',
    'end': '2024-05-02',
    'location': 'Lorem ipsum lorem lorem',
    'id': '1',
  },
  '2': {
    'title': 'Segndou vamo sofrer',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2024-05-08',
    'end': '2024-05-09',
    'location': 'Lorem ipsum lorem lorem',
    'id': '2',
  },
  '3': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2024-05-07',
    'end': '2024-05-07',
    'location': 'Lorem ipsum lorem lorem',
    'id': '3',
  },
  '4': {
    'title': 'Rai4',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2024-05-06',
    'end': '2024-05-10',
    'location': 'Lorem ipsum lorem lorem',
    'id': '4',
  },
  '5': {
    'title': 'Sa',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2024-05-19',
    'end': '2024-05-19',
    'location': 'Lorem ipsum lorem lorem',
    'id': '5',
  },
  '6': {
    'title': 'Rai',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2024-05-19',
    'end': '2024-05-19',
    'location': 'Lorem ipsum lorem lorem',
    'id': '6',
  },
  '7': {
    'title': 'Crazy 87',
    'description': 'Lorem ipsum lorem lorem',
    'start': '2014-10-09',
    'end': '2014-10-09',
    'location': 'Lorem ipsum lorem lorem',
    'id': '7',
  }
}
