export default {
  '1': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-08-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '1',
  },
  '2': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-07-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '2',
  },
  '3': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-07-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '3',
  },
  '4': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-02-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '4',
  },
  '5': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-02-19',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '5',
  },
  '6': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-08-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '6',
  },
  '7': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '7',
  },
  '8': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '8',
  },
  '9': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '9',
  },
  '10': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-11',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '10',
  },
  '11': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-08-12',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '11',
  },
  '12': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-02-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '12',
  },
  '13': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-03-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
    'id': '13',
  },
}
