export default {
  '1': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-08-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '2': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-07-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '3': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-07-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '4': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-02-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '5': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-02-19',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '6': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-08-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '7': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '8': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '9': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '10': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-10-11',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '11': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-08-12',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '12': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-02-10',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
  '13': {
    'title': 'Crazy 8',
    'description': 'Lorem ipsum lorem lorem',
    'date': '2014-03-09',
    'time': '00:30',
    'location': 'Lorem ipsum lorem lorem',
  },
}
